---
title: "GitHub Webscraping"
author: "José Bayoán Santiago Calderón"
date: "2019-06-15"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_knit$set(echo = TRUE)
```


```{r Housekeeping, message=FALSE}
# Housekeeping ----
for (pkg in c("RPostgreSQL", "assertthat", "lubridate", "stringr", "RSelenium",
              "purrr", "maditr", "rvest", "tidyverse")) {
  library(pkg, character.only = TRUE)
}
rm(list = "pkg")
# Initiate Web Driver ----
remDr <- remoteDriver(remoteServerAddr = "selenium_chrome", browserName = "chrome")
remDr$open(silent = TRUE)
```

```{r}
parse_github_contributions <- function(remDr, slug = "jnewland/xhtmlize") {
  
  "https://github.com/${slug}/graphs/contributors" %>%
    str_interp() %>%
    remDr$navigate()
  
    # NEED TO CHECK FOR EMPTY RESULT
  txt <- remDr$findElement(using='css selector',"body")$getElementText()
  while (str_detect(txt, "Crunching the latest data")) {
      Sys.sleep(time = 0.5)
      txt <- remDr$findElement(using='css selector',"body")$getElementText()
    }
  if (str_detect(txt, "We don’t have enough data to show anything useful")) {
    print("No Data")
  } else {
    
    relevant_dates <- remDr$findElement(using = "css", value = "h2") %>%
    (function(x) x$getElementText() %>% getElement(name = 1L))
    relevant_dates <- relevant_dates %>%
      str_extract_all(pattern = "\\p{L}{3} \\d+, \\d+") %>%
      unlist() %>%
      as_date(format = "%b %d, %Y", tz = "UTC")
    login <- remDr$findElements(using = "css",
                            value = "#contributors > ol > li > span > h3 > a.text-normal") %>%
      map_chr(.f = function(x) x$getElementText() %>% getElement(name = 1L))
    commits <- remDr$findElements(using = "css",
                            value = "#contributors > ol > li > span > h3 > span.f6.d-block.text-gray-light > span > a") %>%
      map_int(.f = function(x) x$getElementText() %>% getElement(name = 1L) %>%
                str_remove_all(pattern = ",") %>%
                str_extract(pattern = "\\d+") %>%
                as.integer())
    adds <- remDr$findElements(using = "css",
                            value = "#contributors > ol > li > span > h3 > span.f6.d-block.text-gray-light > span > span.text-green.text-normal") %>%
      map_int(.f = function(x) x$getElementText() %>% getElement(name = 1L) %>%
                str_remove_all(pattern = ",") %>%
                str_extract(pattern = "\\d+") %>%
                as.integer())
    dels <- remDr$findElements(using = "css",
                            value = "#contributors > ol > li > span > h3 > span.f6.d-block.text-gray-light > span > span.text-red.text-normal") %>%
      map_int(.f = function(x) x$getElementText() %>% getElement(name = 1L) %>%
                str_remove_all(pattern = ",") %>%
                str_extract(pattern = "\\d+") %>%
                as.integer())
    value = data.table(login = login,
                       slug = slug,
                       commits = commits,
                       adds = adds,
                       dels = dels)
    
    value2 = data.table(slug = slug,
                        created_on = relevant_dates[1L],
                        last_updated = relevant_dates[2L])
    
    conn <- dbConnect(drv = PostgreSQL(),
                      dbname = "oss",
                      host = "postgis_1",
                      port = 5432L,
                      user = Sys.getenv("db_userid"),
                      password = Sys.getenv("db_pwd"))
  
    # CHECK IF LOGIN & SLUG ALREADY EXISTS IN contributions IF NOT, WRITE TO DB.
    login_slug_exists <- nrow(dbGetQuery(conn, paste0("SELECT * FROM universe.contributions WHERE slug = '", value$slug[1], "'", " AND login = '", value$login, "'")))
    if (login_slug_exists == 0) {
      print(paste0("writing ", value$slug[1], "/", value$login, " to db"))
      dbWriteTable(conn = conn,
                  name = c(schema = "universe", name = "contributions"),
                  value = value,
                  row.names = FALSE,
                  append = TRUE) 
    } else {
      print(paste0(value$slug[1], "/", value$login, " exists"))
    }
    
    # CHECK IF SLUG ALREADY EXISTS IN slugcreatedon. IF NOT, WRITE TO DB.
    slug_exists <- nrow(dbGetQuery(conn, paste0("SELECT * FROM universe.slugcreatedon WHERE slug = '", value2$slug[1], "'")))
    if (slug_exists == 0) {
      print(paste0("writing ", value$slug[1], " to db"))
      dbWriteTable(conn = conn,
                   name = c(schema = "universe", name = "slugcreatedon"),
                   value = value2,
                   row.names = FALSE,
                   append = TRUE)
    } else {
      print(paste0(value$slug[1], " exists"))
    }
  }

  
  
  
  on.exit(expr = remDr$closeall())
  on.exit(expr = dbDisconnect(conn = conn))
  return()
}
```

```{r}
#res <- parse_github_contributions(remDr, "pandas-dev/pandas") # vanpelt/jsawesome pandas-dev/pandas
```

```{r}
# chk <- parse_github_contributions(remDr = remDr,
                                  # slug = "JuliaLang/julia")
# slugs <- 
conn <- dbConnect(drv = PostgreSQL(),
                    dbname = "oss",
                    host = "postgis_1",
                    port = 5432L,
                    user = Sys.getenv("db_userid"),
                    password = Sys.getenv("db_pwd"))
all_slugs <- dbReadTable(conn = conn,
                     name = c(schema = "universe", name = "repo_2008")) %>%
  mutate(slug = str_c(login, "/", reponame)) %>%
  getElement(name = "slug")

slugs_done <- dbReadTable(conn = conn,
                     name = c(schema = "universe", name = "repo_2008")) %>%
  getElement(name = "slug")
slugs <- setdiff(x = all_slugs, y = slugs_done)

dbDisconnect(conn)
#for (slug in slugs) {
 # parse_github_contributions(remDr = remDr, slug = slug)
#}

```

```{r}
#get info
start_time <- Sys.time()
for (slug in slugs[330:3305]) {
  print(slug)
  parse_github_contributions(remDr = remDr, slug = slug)
  Sys.sleep(2)
}
end_time <- Sys.time()
end_time - start_time
#find error
#traceback()

```

